//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\stena\RiderProjects\NppDB\NppDB.MSAccess\MSAccessParser.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="MSAccessParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.CLSCompliant(false)]
public interface IMSAccessParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeyword([NotNull] MSAccessParser.KeywordContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeyword([NotNull] MSAccessParser.KeywordContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.privilege"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrivilege([NotNull] MSAccessParser.PrivilegeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.privilege"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrivilege([NotNull] MSAccessParser.PrivilegeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_name([NotNull] MSAccessParser.Type_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_name([NotNull] MSAccessParser.Type_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.literal_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral_expr([NotNull] MSAccessParser.Literal_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.literal_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral_expr([NotNull] MSAccessParser.Literal_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.column_alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColumn_alias([NotNull] MSAccessParser.Column_aliasContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.column_alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColumn_alias([NotNull] MSAccessParser.Column_aliasContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.any_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAny_name([NotNull] MSAccessParser.Any_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.any_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAny_name([NotNull] MSAccessParser.Any_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterName([NotNull] MSAccessParser.NameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitName([NotNull] MSAccessParser.NameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.function_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_name([NotNull] MSAccessParser.Function_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.function_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_name([NotNull] MSAccessParser.Function_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.table_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTable_name([NotNull] MSAccessParser.Table_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.table_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTable_name([NotNull] MSAccessParser.Table_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.column_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColumn_name([NotNull] MSAccessParser.Column_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.column_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColumn_name([NotNull] MSAccessParser.Column_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.index_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndex_name([NotNull] MSAccessParser.Index_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.index_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndex_name([NotNull] MSAccessParser.Index_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.procedure_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedure_name([NotNull] MSAccessParser.Procedure_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.procedure_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedure_name([NotNull] MSAccessParser.Procedure_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.param_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam_name([NotNull] MSAccessParser.Param_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.param_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam_name([NotNull] MSAccessParser.Param_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.view_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterView_name([NotNull] MSAccessParser.View_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.view_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitView_name([NotNull] MSAccessParser.View_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.table_alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTable_alias([NotNull] MSAccessParser.Table_aliasContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.table_alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTable_alias([NotNull] MSAccessParser.Table_aliasContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.aliased_table_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAliased_table_name([NotNull] MSAccessParser.Aliased_table_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.aliased_table_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAliased_table_name([NotNull] MSAccessParser.Aliased_table_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.direction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDirection([NotNull] MSAccessParser.DirectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.direction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDirection([NotNull] MSAccessParser.DirectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.ordering_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrdering_term([NotNull] MSAccessParser.Ordering_termContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.ordering_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrdering_term([NotNull] MSAccessParser.Ordering_termContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.signed_number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSigned_number([NotNull] MSAccessParser.Signed_numberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.signed_number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSigned_number([NotNull] MSAccessParser.Signed_numberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.param_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam_def([NotNull] MSAccessParser.Param_defContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.param_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam_def([NotNull] MSAccessParser.Param_defContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.optional_parens"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOptional_parens([NotNull] MSAccessParser.Optional_parensContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.optional_parens"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOptional_parens([NotNull] MSAccessParser.Optional_parensContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.default_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefault_expr([NotNull] MSAccessParser.Default_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.default_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefault_expr([NotNull] MSAccessParser.Default_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.column_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColumn_def([NotNull] MSAccessParser.Column_defContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.column_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColumn_def([NotNull] MSAccessParser.Column_defContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.prefixed_star"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrefixed_star([NotNull] MSAccessParser.Prefixed_starContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.prefixed_star"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrefixed_star([NotNull] MSAccessParser.Prefixed_starContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.prefixed_column_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrefixed_column_name([NotNull] MSAccessParser.Prefixed_column_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.prefixed_column_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrefixed_column_name([NotNull] MSAccessParser.Prefixed_column_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.result_column"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterResult_column([NotNull] MSAccessParser.Result_columnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.result_column"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitResult_column([NotNull] MSAccessParser.Result_columnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.param_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam_expr([NotNull] MSAccessParser.Param_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.param_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam_expr([NotNull] MSAccessParser.Param_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.user_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUser_name([NotNull] MSAccessParser.User_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.user_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUser_name([NotNull] MSAccessParser.User_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.group_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGroup_name([NotNull] MSAccessParser.Group_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.group_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGroup_name([NotNull] MSAccessParser.Group_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.user_or_group_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUser_or_group_name([NotNull] MSAccessParser.User_or_group_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.user_or_group_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUser_or_group_name([NotNull] MSAccessParser.User_or_group_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.password"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPassword([NotNull] MSAccessParser.PasswordContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.password"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPassword([NotNull] MSAccessParser.PasswordContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.pid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPid([NotNull] MSAccessParser.PidContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.pid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPid([NotNull] MSAccessParser.PidContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] MSAccessParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] MSAccessParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.function_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_expr([NotNull] MSAccessParser.Function_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.function_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_expr([NotNull] MSAccessParser.Function_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.create_user_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreate_user_stmt([NotNull] MSAccessParser.Create_user_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.create_user_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreate_user_stmt([NotNull] MSAccessParser.Create_user_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.create_group_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreate_group_stmt([NotNull] MSAccessParser.Create_group_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.create_group_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreate_group_stmt([NotNull] MSAccessParser.Create_group_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.drop_user_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDrop_user_stmt([NotNull] MSAccessParser.Drop_user_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.drop_user_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDrop_user_stmt([NotNull] MSAccessParser.Drop_user_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.drop_group_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDrop_group_stmt([NotNull] MSAccessParser.Drop_group_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.drop_group_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDrop_group_stmt([NotNull] MSAccessParser.Drop_group_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.alter_password_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAlter_password_stmt([NotNull] MSAccessParser.Alter_password_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.alter_password_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAlter_password_stmt([NotNull] MSAccessParser.Alter_password_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.add_user_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdd_user_stmt([NotNull] MSAccessParser.Add_user_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.add_user_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdd_user_stmt([NotNull] MSAccessParser.Add_user_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.grant_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGrant_stmt([NotNull] MSAccessParser.Grant_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.grant_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGrant_stmt([NotNull] MSAccessParser.Grant_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.revoke_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRevoke_stmt([NotNull] MSAccessParser.Revoke_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.revoke_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRevoke_stmt([NotNull] MSAccessParser.Revoke_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.alter_table_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAlter_table_stmt([NotNull] MSAccessParser.Alter_table_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.alter_table_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAlter_table_stmt([NotNull] MSAccessParser.Alter_table_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.begin_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBegin_stmt([NotNull] MSAccessParser.Begin_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.begin_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBegin_stmt([NotNull] MSAccessParser.Begin_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.commit_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommit_stmt([NotNull] MSAccessParser.Commit_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.commit_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommit_stmt([NotNull] MSAccessParser.Commit_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.rollback_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRollback_stmt([NotNull] MSAccessParser.Rollback_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.rollback_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRollback_stmt([NotNull] MSAccessParser.Rollback_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.on_trigger"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOn_trigger([NotNull] MSAccessParser.On_triggerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.on_trigger"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOn_trigger([NotNull] MSAccessParser.On_triggerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.single_field_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSingle_field_constraint([NotNull] MSAccessParser.Single_field_constraintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.single_field_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSingle_field_constraint([NotNull] MSAccessParser.Single_field_constraintContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.multiple_field_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiple_field_constraint([NotNull] MSAccessParser.Multiple_field_constraintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.multiple_field_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiple_field_constraint([NotNull] MSAccessParser.Multiple_field_constraintContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.exec_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExec_stmt([NotNull] MSAccessParser.Exec_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.exec_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExec_stmt([NotNull] MSAccessParser.Exec_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.create_table_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreate_table_stmt([NotNull] MSAccessParser.Create_table_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.create_table_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreate_table_stmt([NotNull] MSAccessParser.Create_table_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.create_view_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreate_view_stmt([NotNull] MSAccessParser.Create_view_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.create_view_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreate_view_stmt([NotNull] MSAccessParser.Create_view_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.create_index_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreate_index_stmt([NotNull] MSAccessParser.Create_index_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.create_index_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreate_index_stmt([NotNull] MSAccessParser.Create_index_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.create_procedure_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCreate_procedure_stmt([NotNull] MSAccessParser.Create_procedure_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.create_procedure_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCreate_procedure_stmt([NotNull] MSAccessParser.Create_procedure_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.drop_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDrop_stmt([NotNull] MSAccessParser.Drop_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.drop_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDrop_stmt([NotNull] MSAccessParser.Drop_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.select_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelect_stmt([NotNull] MSAccessParser.Select_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.select_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelect_stmt([NotNull] MSAccessParser.Select_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.table_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTable_stmt([NotNull] MSAccessParser.Table_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.table_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTable_stmt([NotNull] MSAccessParser.Table_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.table_core_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTable_core_stmt([NotNull] MSAccessParser.Table_core_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.table_core_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTable_core_stmt([NotNull] MSAccessParser.Table_core_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.select_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelect_clause([NotNull] MSAccessParser.Select_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.select_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelect_clause([NotNull] MSAccessParser.Select_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.select_into_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelect_into_stmt([NotNull] MSAccessParser.Select_into_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.select_into_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelect_into_stmt([NotNull] MSAccessParser.Select_into_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.select_core_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelect_core_stmt([NotNull] MSAccessParser.Select_core_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.select_core_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelect_core_stmt([NotNull] MSAccessParser.Select_core_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.table_or_subquery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTable_or_subquery([NotNull] MSAccessParser.Table_or_subqueryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.table_or_subquery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTable_or_subquery([NotNull] MSAccessParser.Table_or_subqueryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.table_with_joins"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTable_with_joins([NotNull] MSAccessParser.Table_with_joinsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.table_with_joins"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTable_with_joins([NotNull] MSAccessParser.Table_with_joinsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.from_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFrom_clause([NotNull] MSAccessParser.From_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.from_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFrom_clause([NotNull] MSAccessParser.From_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.join_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJoin_clause([NotNull] MSAccessParser.Join_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.join_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJoin_clause([NotNull] MSAccessParser.Join_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.where_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhere_clause([NotNull] MSAccessParser.Where_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.where_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhere_clause([NotNull] MSAccessParser.Where_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.group_by_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGroup_by_clause([NotNull] MSAccessParser.Group_by_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.group_by_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGroup_by_clause([NotNull] MSAccessParser.Group_by_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.order_by_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrder_by_clause([NotNull] MSAccessParser.Order_by_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.order_by_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrder_by_clause([NotNull] MSAccessParser.Order_by_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.insert_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInsert_stmt([NotNull] MSAccessParser.Insert_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.insert_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInsert_stmt([NotNull] MSAccessParser.Insert_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.update_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUpdate_stmt([NotNull] MSAccessParser.Update_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.update_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUpdate_stmt([NotNull] MSAccessParser.Update_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.delete_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDelete_stmt([NotNull] MSAccessParser.Delete_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.delete_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDelete_stmt([NotNull] MSAccessParser.Delete_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.procedure_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedure_stmt([NotNull] MSAccessParser.Procedure_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.procedure_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedure_stmt([NotNull] MSAccessParser.Procedure_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.parameters_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameters_stmt([NotNull] MSAccessParser.Parameters_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.parameters_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameters_stmt([NotNull] MSAccessParser.Parameters_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.sql_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSql_stmt([NotNull] MSAccessParser.Sql_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.sql_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSql_stmt([NotNull] MSAccessParser.Sql_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.sql_stmt_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSql_stmt_list([NotNull] MSAccessParser.Sql_stmt_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.sql_stmt_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSql_stmt_list([NotNull] MSAccessParser.Sql_stmt_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.parse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParse([NotNull] MSAccessParser.ParseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.parse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParse([NotNull] MSAccessParser.ParseContext context);
}
