//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\perekond Post\Desktop\NppDB\NppDB\NppDB.MSAccess\MSAccessParser.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IMSAccessParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class MSAccessParserBaseListener : IMSAccessParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKeyword([NotNull] MSAccessParser.KeywordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKeyword([NotNull] MSAccessParser.KeywordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.privilege"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrivilege([NotNull] MSAccessParser.PrivilegeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.privilege"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrivilege([NotNull] MSAccessParser.PrivilegeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.type_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_name([NotNull] MSAccessParser.Type_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.type_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_name([NotNull] MSAccessParser.Type_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.literal_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral_expr([NotNull] MSAccessParser.Literal_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.literal_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral_expr([NotNull] MSAccessParser.Literal_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.column_alias"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterColumn_alias([NotNull] MSAccessParser.Column_aliasContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.column_alias"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitColumn_alias([NotNull] MSAccessParser.Column_aliasContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.any_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAny_name([NotNull] MSAccessParser.Any_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.any_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAny_name([NotNull] MSAccessParser.Any_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterName([NotNull] MSAccessParser.NameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitName([NotNull] MSAccessParser.NameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.function_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_name([NotNull] MSAccessParser.Function_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.function_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_name([NotNull] MSAccessParser.Function_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.table_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTable_name([NotNull] MSAccessParser.Table_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.table_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTable_name([NotNull] MSAccessParser.Table_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.column_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterColumn_name([NotNull] MSAccessParser.Column_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.column_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitColumn_name([NotNull] MSAccessParser.Column_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.index_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndex_name([NotNull] MSAccessParser.Index_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.index_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndex_name([NotNull] MSAccessParser.Index_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.procedure_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcedure_name([NotNull] MSAccessParser.Procedure_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.procedure_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcedure_name([NotNull] MSAccessParser.Procedure_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.param_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParam_name([NotNull] MSAccessParser.Param_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.param_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParam_name([NotNull] MSAccessParser.Param_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.view_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterView_name([NotNull] MSAccessParser.View_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.view_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitView_name([NotNull] MSAccessParser.View_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.table_alias"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTable_alias([NotNull] MSAccessParser.Table_aliasContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.table_alias"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTable_alias([NotNull] MSAccessParser.Table_aliasContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.aliased_table_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAliased_table_name([NotNull] MSAccessParser.Aliased_table_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.aliased_table_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAliased_table_name([NotNull] MSAccessParser.Aliased_table_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.direction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirection([NotNull] MSAccessParser.DirectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.direction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirection([NotNull] MSAccessParser.DirectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.ordering_term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrdering_term([NotNull] MSAccessParser.Ordering_termContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.ordering_term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrdering_term([NotNull] MSAccessParser.Ordering_termContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.signed_number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSigned_number([NotNull] MSAccessParser.Signed_numberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.signed_number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSigned_number([NotNull] MSAccessParser.Signed_numberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.param_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParam_def([NotNull] MSAccessParser.Param_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.param_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParam_def([NotNull] MSAccessParser.Param_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.optional_parens"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOptional_parens([NotNull] MSAccessParser.Optional_parensContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.optional_parens"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOptional_parens([NotNull] MSAccessParser.Optional_parensContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.default_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefault_expr([NotNull] MSAccessParser.Default_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.default_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefault_expr([NotNull] MSAccessParser.Default_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.column_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterColumn_def([NotNull] MSAccessParser.Column_defContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.column_def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitColumn_def([NotNull] MSAccessParser.Column_defContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.prefixed_star"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrefixed_star([NotNull] MSAccessParser.Prefixed_starContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.prefixed_star"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrefixed_star([NotNull] MSAccessParser.Prefixed_starContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.prefixed_column_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrefixed_column_name([NotNull] MSAccessParser.Prefixed_column_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.prefixed_column_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrefixed_column_name([NotNull] MSAccessParser.Prefixed_column_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.result_column"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterResult_column([NotNull] MSAccessParser.Result_columnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.result_column"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitResult_column([NotNull] MSAccessParser.Result_columnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.param_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParam_expr([NotNull] MSAccessParser.Param_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.param_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParam_expr([NotNull] MSAccessParser.Param_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.user_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUser_name([NotNull] MSAccessParser.User_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.user_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUser_name([NotNull] MSAccessParser.User_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.group_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGroup_name([NotNull] MSAccessParser.Group_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.group_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGroup_name([NotNull] MSAccessParser.Group_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.user_or_group_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUser_or_group_name([NotNull] MSAccessParser.User_or_group_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.user_or_group_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUser_or_group_name([NotNull] MSAccessParser.User_or_group_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.password"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPassword([NotNull] MSAccessParser.PasswordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.password"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPassword([NotNull] MSAccessParser.PasswordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.pid"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPid([NotNull] MSAccessParser.PidContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.pid"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPid([NotNull] MSAccessParser.PidContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] MSAccessParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] MSAccessParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.function_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_expr([NotNull] MSAccessParser.Function_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.function_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_expr([NotNull] MSAccessParser.Function_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.create_user_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCreate_user_stmt([NotNull] MSAccessParser.Create_user_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.create_user_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCreate_user_stmt([NotNull] MSAccessParser.Create_user_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.create_group_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCreate_group_stmt([NotNull] MSAccessParser.Create_group_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.create_group_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCreate_group_stmt([NotNull] MSAccessParser.Create_group_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.drop_user_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDrop_user_stmt([NotNull] MSAccessParser.Drop_user_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.drop_user_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDrop_user_stmt([NotNull] MSAccessParser.Drop_user_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.drop_group_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDrop_group_stmt([NotNull] MSAccessParser.Drop_group_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.drop_group_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDrop_group_stmt([NotNull] MSAccessParser.Drop_group_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.alter_password_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAlter_password_stmt([NotNull] MSAccessParser.Alter_password_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.alter_password_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAlter_password_stmt([NotNull] MSAccessParser.Alter_password_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.add_user_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdd_user_stmt([NotNull] MSAccessParser.Add_user_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.add_user_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdd_user_stmt([NotNull] MSAccessParser.Add_user_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.grant_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGrant_stmt([NotNull] MSAccessParser.Grant_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.grant_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGrant_stmt([NotNull] MSAccessParser.Grant_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.revoke_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRevoke_stmt([NotNull] MSAccessParser.Revoke_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.revoke_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRevoke_stmt([NotNull] MSAccessParser.Revoke_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.alter_table_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAlter_table_stmt([NotNull] MSAccessParser.Alter_table_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.alter_table_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAlter_table_stmt([NotNull] MSAccessParser.Alter_table_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.begin_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBegin_stmt([NotNull] MSAccessParser.Begin_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.begin_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBegin_stmt([NotNull] MSAccessParser.Begin_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.commit_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommit_stmt([NotNull] MSAccessParser.Commit_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.commit_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommit_stmt([NotNull] MSAccessParser.Commit_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.rollback_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRollback_stmt([NotNull] MSAccessParser.Rollback_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.rollback_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRollback_stmt([NotNull] MSAccessParser.Rollback_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.on_trigger"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOn_trigger([NotNull] MSAccessParser.On_triggerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.on_trigger"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOn_trigger([NotNull] MSAccessParser.On_triggerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.single_field_constraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSingle_field_constraint([NotNull] MSAccessParser.Single_field_constraintContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.single_field_constraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSingle_field_constraint([NotNull] MSAccessParser.Single_field_constraintContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.multiple_field_constraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiple_field_constraint([NotNull] MSAccessParser.Multiple_field_constraintContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.multiple_field_constraint"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiple_field_constraint([NotNull] MSAccessParser.Multiple_field_constraintContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.exec_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExec_stmt([NotNull] MSAccessParser.Exec_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.exec_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExec_stmt([NotNull] MSAccessParser.Exec_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.create_table_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCreate_table_stmt([NotNull] MSAccessParser.Create_table_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.create_table_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCreate_table_stmt([NotNull] MSAccessParser.Create_table_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.create_view_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCreate_view_stmt([NotNull] MSAccessParser.Create_view_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.create_view_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCreate_view_stmt([NotNull] MSAccessParser.Create_view_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.create_index_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCreate_index_stmt([NotNull] MSAccessParser.Create_index_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.create_index_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCreate_index_stmt([NotNull] MSAccessParser.Create_index_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.create_procedure_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCreate_procedure_stmt([NotNull] MSAccessParser.Create_procedure_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.create_procedure_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCreate_procedure_stmt([NotNull] MSAccessParser.Create_procedure_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.drop_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDrop_stmt([NotNull] MSAccessParser.Drop_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.drop_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDrop_stmt([NotNull] MSAccessParser.Drop_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.select_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelect_stmt([NotNull] MSAccessParser.Select_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.select_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelect_stmt([NotNull] MSAccessParser.Select_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.table_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTable_stmt([NotNull] MSAccessParser.Table_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.table_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTable_stmt([NotNull] MSAccessParser.Table_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.table_core_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTable_core_stmt([NotNull] MSAccessParser.Table_core_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.table_core_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTable_core_stmt([NotNull] MSAccessParser.Table_core_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.select_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelect_clause([NotNull] MSAccessParser.Select_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.select_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelect_clause([NotNull] MSAccessParser.Select_clauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.select_into_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelect_into_stmt([NotNull] MSAccessParser.Select_into_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.select_into_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelect_into_stmt([NotNull] MSAccessParser.Select_into_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.select_core_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelect_core_stmt([NotNull] MSAccessParser.Select_core_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.select_core_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelect_core_stmt([NotNull] MSAccessParser.Select_core_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.table_or_subquery"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTable_or_subquery([NotNull] MSAccessParser.Table_or_subqueryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.table_or_subquery"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTable_or_subquery([NotNull] MSAccessParser.Table_or_subqueryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.table_with_joins"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTable_with_joins([NotNull] MSAccessParser.Table_with_joinsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.table_with_joins"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTable_with_joins([NotNull] MSAccessParser.Table_with_joinsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.from_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFrom_clause([NotNull] MSAccessParser.From_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.from_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFrom_clause([NotNull] MSAccessParser.From_clauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.join_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJoin_clause([NotNull] MSAccessParser.Join_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.join_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJoin_clause([NotNull] MSAccessParser.Join_clauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.where_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhere_clause([NotNull] MSAccessParser.Where_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.where_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhere_clause([NotNull] MSAccessParser.Where_clauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.group_by_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGroup_by_clause([NotNull] MSAccessParser.Group_by_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.group_by_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGroup_by_clause([NotNull] MSAccessParser.Group_by_clauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.order_by_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrder_by_clause([NotNull] MSAccessParser.Order_by_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.order_by_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrder_by_clause([NotNull] MSAccessParser.Order_by_clauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.insert_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInsert_stmt([NotNull] MSAccessParser.Insert_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.insert_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInsert_stmt([NotNull] MSAccessParser.Insert_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.update_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUpdate_stmt([NotNull] MSAccessParser.Update_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.update_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUpdate_stmt([NotNull] MSAccessParser.Update_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.delete_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDelete_stmt([NotNull] MSAccessParser.Delete_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.delete_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDelete_stmt([NotNull] MSAccessParser.Delete_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.procedure_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcedure_stmt([NotNull] MSAccessParser.Procedure_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.procedure_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcedure_stmt([NotNull] MSAccessParser.Procedure_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.parameters_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameters_stmt([NotNull] MSAccessParser.Parameters_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.parameters_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameters_stmt([NotNull] MSAccessParser.Parameters_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.sql_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSql_stmt([NotNull] MSAccessParser.Sql_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.sql_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSql_stmt([NotNull] MSAccessParser.Sql_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.sql_stmt_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSql_stmt_list([NotNull] MSAccessParser.Sql_stmt_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.sql_stmt_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSql_stmt_list([NotNull] MSAccessParser.Sql_stmt_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MSAccessParser.parse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParse([NotNull] MSAccessParser.ParseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MSAccessParser.parse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParse([NotNull] MSAccessParser.ParseContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
